use crate::types::{AgentNotification, CostSnapshot, LimitWindow, ModelInfo, ProviderStatus};
use async_trait::async_trait;

/// Contract every provider plugin must implement. Plugins are the only place
/// that know about a specific vendor's quirks — everything downstream only
/// ever sees `ProviderStatus`.
#[async_trait]
pub trait ProviderPlugin: Send + Sync {
    fn id(&self) -> &str;
    fn display_name(&self) -> &str;
    /// Suggested polling interval; the scheduler may throttle further under
    /// battery/idle conditions.
    fn refresh_interval_ms(&self) -> u64;

    /// Best-effort check for whether this provider is usable on this machine
    /// (config file present, CLI on PATH, API key set, local server reachable).
    /// Must not panic; return false on any doubt.
    async fn detect(&self) -> bool;

    /// Pull a fresh reading. Called on the plugin's own refresh cadence and on
    /// manual refresh from the UI.
    async fn refresh(&mut self);

    /// Return the last-known status without triggering a network/IO call.
    fn get_status(&self) -> ProviderStatus;

    fn get_limits(&self) -> Vec<LimitWindow> {
        self.get_status().limits
    }

    fn get_usage(&self) -> Option<CostSnapshot> {
        self.get_status().cost
    }

    fn get_models(&self) -> Vec<ModelInfo> {
        self.get_status().models
    }

    /// Notifications generated by this plugin since the last drain (provider-specific
    /// events; threshold-crossing notifications are computed centrally instead — see
    /// the `agent-notifications` crate).
    fn drain_notifications(&mut self) -> Vec<AgentNotification> {
        Vec::new()
    }
}
